package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("clusterRoleSelectors")
class AggregationRule_rbac_authorization_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: AggregationRule_rbac_authorization_k8s_io_v1_k8s1_16, HasParent {
  override var clusterRoleSelectors: List<LabelSelector_meta_v1_k8s1_16>? = null
}
typealias AggregationRule_rbac_authorization_k8s_io_v1_k8s1_17Impl = AggregationRule_rbac_authorization_k8s_io_v1_k8s1_16Impl
typealias AggregationRule_rbac_authorization_k8s_io_v1_k8s1_18Impl = AggregationRule_rbac_authorization_k8s_io_v1_k8s1_17Impl
typealias AggregationRule_rbac_authorization_k8s_io_v1_k8s1_19Impl = AggregationRule_rbac_authorization_k8s_io_v1_k8s1_18Impl
typealias AggregationRule_rbac_authorization_k8s_io_v1_k8s1_20Impl = AggregationRule_rbac_authorization_k8s_io_v1_k8s1_19Impl
typealias AggregationRule_rbac_authorization_k8s_io_v1_k8s1_21Impl = AggregationRule_rbac_authorization_k8s_io_v1_k8s1_20Impl