package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("scale", "status")
class CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  override var scale: CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_16? = null
  override var status: CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_16? = null
}
typealias CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_17Impl = CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_16Impl
typealias CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_18Impl = CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_17Impl
typealias CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_19Impl = CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_18Impl
typealias CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_20Impl = CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_19Impl
typealias CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_21Impl = CustomResourceSubresources_apiextensions_k8s_io_v1_k8s1_20Impl