package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("labelSelectorPath", "specReplicasPath", "statusReplicasPath")
class CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  override var labelSelectorPath: String? = null
  override var specReplicasPath: String? = null
  override var statusReplicasPath: String? = null
}
typealias CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_17Impl = CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_16Impl
typealias CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_18Impl = CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_17Impl
typealias CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_19Impl = CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_18Impl
typealias CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_20Impl = CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_19Impl
typealias CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_21Impl = CustomResourceSubresourceScale_apiextensions_k8s_io_v1_k8s1_20Impl