package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("openAPIV3Schema")
class CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  override var openAPIV3Schema: JSONSchemaProps_apiextensions_k8s_io_v1_k8s1_16? = null
}
typealias CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_17Impl = CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_16Impl
typealias CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_18Impl = CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_17Impl
typealias CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_19Impl = CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_18Impl
typealias CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_20Impl = CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_19Impl
typealias CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_21Impl = CustomResourceValidation_apiextensions_k8s_io_v1_k8s1_20Impl