package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("strategy", "webhook")
class CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  override var strategy: String? = null
  override var webhook: WebhookConversion_apiextensions_k8s_io_v1_k8s1_16? = null
}
typealias CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_17Impl = CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_16Impl
typealias CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_18Impl = CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_17Impl
typealias CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_19Impl = CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_18Impl
typealias CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_20Impl = CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_19Impl
typealias CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_21Impl = CustomResourceConversion_apiextensions_k8s_io_v1_k8s1_20Impl