package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("")
class CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  
}
typealias CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_17Impl = CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_16Impl
typealias CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_18Impl = CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_17Impl
typealias CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_19Impl = CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_18Impl
typealias CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_20Impl = CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_19Impl
typealias CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_21Impl = CustomResourceSubresourceStatus_apiextensions_k8s_io_v1_k8s1_20Impl