package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("")
class JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  
}
typealias JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_17Impl = JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_16Impl
typealias JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_18Impl = JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_17Impl
typealias JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_19Impl = JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_18Impl
typealias JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_20Impl = JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_19Impl
typealias JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_21Impl = JSONSchemaPropsOrBool_apiextensions_k8s_io_v1_k8s1_20Impl