package de.loosetie.k8s.dsl.impls

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import de.loosetie.k8s.dsl.K8sManifest
import de.loosetie.k8s.dsl.HasParent
import de.loosetie.k8s.dsl.manifests.*

@JsonPropertyOrder("")
class JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_16Impl(
  @JsonIgnore
  override val parent: K8sManifest? = null
)
: JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_16, HasParent {
  
}
typealias JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_17Impl = JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_16Impl
typealias JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_18Impl = JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_17Impl
typealias JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_19Impl = JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_18Impl
typealias JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_20Impl = JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_19Impl
typealias JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_21Impl = JSONSchemaPropsOrArray_apiextensions_k8s_io_v1_k8s1_20Impl